class Plant{
  String image;
  String title;
  String info;
  Plant({required this.image,required this.title,required this.info});
}
final plantlist = [
  Plant(image: "https://i.pinimg.com/236x/aa/d0/7b/aad07bfc3fa4fd9c40955ffe1fcb5226.jpg",title: 'Mersedes',info: "Mercedes-Benz W463 — второе поколение внедорожников G-класса немецкой торговой марки Mercedes-Benz. Представлено в 1990 году для замены модели Mercedes-Benz W460. По сравнению с предшественником новое поколение получило достаточно много обновлений: полный пересмотр ходовой части, оснащение постоянным полным приводом, внедрение антиблокировочной системы и трёх электрически блокируемых дифференциалов, установка абсолютно нового интерьера с деревянными вставками и возможностью применения кожаной отделки в салоне. Модельный ряд двигателей также значительно расширился и к 1993 году пополнился топовой модификацией G 500 с двигателем V8.", ),
  Plant(image:"https://i.pinimg.com/236x/6f/a3/8a/6fa38a17702d825b6379df5913cc6c34.jpg",title: 'BMW',info:"BMW M5 — доработанная подразделением BMW Motorsport версия автомобиля BMW пятой серии. Первое поколение было представлено в 1986 году. Последующие поколения M5 сменялись совместно с каждым поколением автомобилей пятой серии, включающей E34, E39, E60/61, F10. С началом производства модели G30, после поступления первых заказов, с марта 2018 года началось также производство её M-версии.", ),
  Plant(image:"https://i.pinimg.com/236x/b8/04/a6/b804a6f05e834386996a370a4473b6ae.jp",title: 'Supra',info:"First introduced in 1993, the MK4 was designed to be a high-performance sports car that could compete with some of the best vehicles on the market. It was powered by a turbocharged inline-six engine that produced up to 320 horsepower and 315 lb-ft of torque, making it one of the most powerful cars of its time.", ),
  Plant(image:"https://i.pinimg.com/236x/dd/e1/9f/dde19f4788553d98cb8493dafb4235f5.jpg",title: 'Gtr',info: "The Nissan Skyline GT-R (Japanese: 日産・スカイラインGT-R, Hepburn: Nissan Sukairain GT-R) is a Japanese sports car based on the Nissan Skyline range. The first cars named Skyline GT-R were produced between 1969 and 1972 under the model code KPGC10, and were successful in Japanese touring car racing events. This model was followed by a brief production run of second-generation cars, under model code KPGC110, in 1973.", ),
  Plant(image: "https://i.pinimg.com/236x/15/90/64/159064a54824ba41343c95a61317d9a8.jpg", title:"Efil Tower", info: "The Eiffel Tower (/ˈaɪfəl/ EYE-fəl; French: tour Eiffel [tuʁ ɛfɛl] (listen)) is a wrought-iron lattice tower on the Champ de Mars in Paris, France. Constructed from 1887, it is named after the engineer Gustave Eiffel, whose company designed and built the tower.Locally nicknamed La dame de fer French for Iron Lady, it was constructed from 1887 to 1889 as the centerpiece of the 1889 World's Fair. "),
  Plant(image: "https://i.pinimg.com/236x/59/ea/b6/59eab6a1a7ba6d3b9f2aaee93505cf4a.jpg", title:"Burj Halifa", info: "The Burj Khalifa[a] (known as the Burj Dubai prior to its inauguration in 2010) is a skyscraper in Dubai, United Arab Emirates. It is the world's tallest building. With a total height of 829.8 m (2,722 ft, or just over half a mile) and a roof height (excluding antenna, but including a 242.6 m spire[2]) of 828 m (2,717 ft), the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009, supplanting Taipei 101, the previous holder of that status."),
  Plant(image: "https://i.pinimg.com/236x/45/8a/3f/458a3f4648938c89c72ca6e09dd25a47.jpg", title:"Apple", info: "iPhone is a line of smartphones produced by Apple Inc. that use Apple's own iOS mobile operating system. The first-generation iPhone was announced by then-Apple CEO Steve Jobs on January 9, 2007. Since then, Apple has annually released new iPhone models and iOS updates. As of November 1, 2018, more than 2.2 billion iPhones had been sold. As of 2022, the iPhone accounts for 15.6% of global smartphone market share."),
  Plant(image: "https://i.pinimg.com/236x/1e/ff/ee/1effee290771b47c4d04d95f868f680d.jpg", title:"Samsung", info: "Samsung Group,[3] or simply Samsung (Korean: 삼성; RR: samseong [samsʌŋ]) (stylized as SΛMSUNG), is a South Korean multinational manufacturing conglomerate headquartered in Samsung Digital City, Suwon, South Korea.[1] It comprises numerous affiliated businesses,[1] most of them united under the Samsung brand, and is the largest South Korean chaebol (business conglomerate). As of 2020, Samsung has the eighth highest global brand value.["),
 ];